# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: #FFFFFF;\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.overheader = QtWidgets.QFrame(self.centralwidget)
        self.overheader.setMinimumSize(QtCore.QSize(0, 30))
        self.overheader.setMaximumSize(QtCore.QSize(16777215, 30))
        self.overheader.setFrameShape(QtWidgets.QFrame.Panel)
        self.overheader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.overheader.setObjectName("overheader")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.overheader)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.top_left_btns = QtWidgets.QFrame(self.overheader)
        self.top_left_btns.setMinimumSize(QtCore.QSize(42, 0))
        self.top_left_btns.setMaximumSize(QtCore.QSize(42, 16777215))
        self.top_left_btns.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"    border-radius: 5px; \n"
"    transition: all 0.5s;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-top: 2px solid rgb(0, 234, 153);\n"
"}")
        self.top_left_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_left_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_left_btns.setObjectName("top_left_btns")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.top_left_btns)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.menuButton = QtWidgets.QPushButton(self.top_left_btns)
        self.menuButton.setMinimumSize(QtCore.QSize(30, 30))
        self.menuButton.setMaximumSize(QtCore.QSize(1000000, 30))
        self.menuButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.menuButton.setStyleSheet("")
        self.menuButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/assets/menuButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuButton.setIcon(icon)
        self.menuButton.setObjectName("menuButton")
        self.horizontalLayout_6.addWidget(self.menuButton)
        self.horizontalLayout_5.addWidget(self.top_left_btns, 0, QtCore.Qt.AlignLeft)
        self.Name = QtWidgets.QFrame(self.overheader)
        self.Name.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Name.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Name.setObjectName("Name")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Name)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.RateX = QtWidgets.QLabel(self.Name)
        self.RateX.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.RateX.setFont(font)
        self.RateX.setStyleSheet("border-radius: 9px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 255), stop:1 rgba(14, 177, 255, 255));\n"
"color: #fff;\n"
"")
        self.RateX.setAlignment(QtCore.Qt.AlignCenter)
        self.RateX.setObjectName("RateX")
        self.horizontalLayout_4.addWidget(self.RateX, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_5.addWidget(self.Name, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.top_right_btns = QtWidgets.QFrame(self.overheader)
        self.top_right_btns.setMaximumSize(QtCore.QSize(180, 16777215))
        self.top_right_btns.setStyleSheet("QPushButton {\n"
"    border:none;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.top_right_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.top_right_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_right_btns.setObjectName("top_right_btns")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_right_btns)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.minimizeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.minimizeButton.setMinimumSize(QtCore.QSize(60, 30))
        self.minimizeButton.setMaximumSize(QtCore.QSize(60, 30))
        self.minimizeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.minimizeButton.setStyleSheet("")
        self.minimizeButton.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/assets/minimizeButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.minimizeButton.setIcon(icon1)
        self.minimizeButton.setIconSize(QtCore.QSize(16, 16))
        self.minimizeButton.setObjectName("minimizeButton")
        self.horizontalLayout_3.addWidget(self.minimizeButton)
        self.restoreButton = QtWidgets.QPushButton(self.top_right_btns)
        self.restoreButton.setMinimumSize(QtCore.QSize(60, 30))
        self.restoreButton.setMaximumSize(QtCore.QSize(60, 30))
        self.restoreButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.restoreButton.setStyleSheet("")
        self.restoreButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/assets/restoreButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.restoreButton.setIcon(icon2)
        self.restoreButton.setIconSize(QtCore.QSize(16, 16))
        self.restoreButton.setObjectName("restoreButton")
        self.horizontalLayout_3.addWidget(self.restoreButton)
        self.closeButton = QtWidgets.QPushButton(self.top_right_btns)
        self.closeButton.setMinimumSize(QtCore.QSize(60, 30))
        self.closeButton.setMaximumSize(QtCore.QSize(60, 30))
        self.closeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeButton.setStyleSheet("QPushButton:hover {\n"
"    background-color: rgb(255, 194, 194);\n"
"}")
        self.closeButton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/assets/closeButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.closeButton.setIcon(icon3)
        self.closeButton.setIconSize(QtCore.QSize(16, 16))
        self.closeButton.setObjectName("closeButton")
        self.horizontalLayout_3.addWidget(self.closeButton)
        self.horizontalLayout_5.addWidget(self.top_right_btns, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignTop)
        self.verticalLayout.addWidget(self.overheader)
        self.main_header = QtWidgets.QFrame(self.centralwidget)
        self.main_header.setMinimumSize(QtCore.QSize(0, 60))
        self.main_header.setMaximumSize(QtCore.QSize(16777215, 60))
        self.main_header.setStyleSheet("background-color: rgb(240, 255, 240);")
        self.main_header.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_header.setObjectName("main_header")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.main_header)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_menu_toogle = QtWidgets.QFrame(self.main_header)
        self.left_menu_toogle.setMaximumSize(QtCore.QSize(120, 16777215))
        self.left_menu_toogle.setStyleSheet("border: none;")
        self.left_menu_toogle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.left_menu_toogle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_menu_toogle.setObjectName("left_menu_toogle")
        self.Rate = QtWidgets.QPushButton(self.left_menu_toogle)
        self.Rate.setGeometry(QtCore.QRect(0, 0, 91, 61))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.Rate.setFont(font)
        self.Rate.setObjectName("Rate")
        self.X = QtWidgets.QPushButton(self.left_menu_toogle)
        self.X.setGeometry(QtCore.QRect(80, 0, 41, 61))
        self.X.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/assets/MainWindowLogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.X.setIcon(icon4)
        self.X.setIconSize(QtCore.QSize(35, 35))
        self.X.setObjectName("X")
        self.horizontalLayout_2.addWidget(self.left_menu_toogle)
        self.title_bar = QtWidgets.QFrame(self.main_header)
        self.title_bar.setStyleSheet("")
        self.title_bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.title_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.title_bar.setObjectName("title_bar")
        self.horizontalLayout_2.addWidget(self.title_bar)
        self.right_menu_toogle = QtWidgets.QFrame(self.main_header)
        self.right_menu_toogle.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    transition: all 0.5s;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(215, 228, 215);\n"
"}\n"
"QPushButton:pressed {\n"
"    border-top: 6px solid rgb(32, 225, 175);\n"
"    border-bottom: 6px solid rgb(8, 176, 231);\n"
"}")
        self.right_menu_toogle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_menu_toogle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_menu_toogle.setObjectName("right_menu_toogle")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.right_menu_toogle)
        self.horizontalLayout_8.setContentsMargins(0, 0, 4, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.rightButtonMenu = QtWidgets.QPushButton(self.right_menu_toogle)
        self.rightButtonMenu.setMinimumSize(QtCore.QSize(50, 50))
        self.rightButtonMenu.setMaximumSize(QtCore.QSize(50, 50))
        self.rightButtonMenu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.rightButtonMenu.setStyleSheet("border: none;\n"
"border-radius: 25px;\n"
"")
        self.rightButtonMenu.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/assets/dollar.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rightButtonMenu.setIcon(icon5)
        self.rightButtonMenu.setIconSize(QtCore.QSize(50, 50))
        self.rightButtonMenu.setObjectName("rightButtonMenu")
        self.horizontalLayout_8.addWidget(self.rightButtonMenu)
        self.horizontalLayout_2.addWidget(self.right_menu_toogle, 0, QtCore.Qt.AlignRight)
        self.verticalLayout.addWidget(self.main_header)
        self.main_body = QtWidgets.QFrame(self.centralwidget)
        self.main_body.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.main_body.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_body.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_body.setObjectName("main_body")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.main_body)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_side_menu = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_side_menu.sizePolicy().hasHeightForWidth())
        self.left_side_menu.setSizePolicy(sizePolicy)
        self.left_side_menu.setMinimumSize(QtCore.QSize(50, 0))
        self.left_side_menu.setMaximumSize(QtCore.QSize(50, 16777215))
        self.left_side_menu.setSizeIncrement(QtCore.QSize(150, 0))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.left_side_menu.setFont(font)
        self.left_side_menu.setStyleSheet("QPushButton {\n"
"    background-color: rgb(240, 255, 240);\n"
"    border-radius: 20px;\n"
"    background-color: rgb(240, 240, 240);\n"
"    color: #000;\n"
"    transition: all 0.5s;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 255), stop:1 rgba(14, 177, 255, 255));\n"
"    color: #fff;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-bottom: 2px solid rgb(0, 234, 153);\n"
"}")
        self.left_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_side_menu.setObjectName("left_side_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.left_side_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.left_menu_top_buttons = QtWidgets.QFrame(self.left_side_menu)
        self.left_menu_top_buttons.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.left_menu_top_buttons.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_menu_top_buttons.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.left_menu_top_buttons.setObjectName("left_menu_top_buttons")
        self.formLayout = QtWidgets.QFormLayout(self.left_menu_top_buttons)
        self.formLayout.setContentsMargins(0, 5, 0, 0)
        self.formLayout.setHorizontalSpacing(0)
        self.formLayout.setVerticalSpacing(5)
        self.formLayout.setObjectName("formLayout")
        self.CurrencyRateCharts_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.CurrencyRateCharts_button.setMinimumSize(QtCore.QSize(0, 40))
        self.CurrencyRateCharts_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.CurrencyRateCharts_button.setFont(font)
        self.CurrencyRateCharts_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CurrencyRateCharts_button.setStyleSheet("QPushButton {\n"
"    border-bottom: 2px solid rgb(0, 234, 153);\n"
"    background-image: url(:/images/assets/CurrencyRateChartsBlack.png);\n"
"    background-repeat: none;\n"
"    padding-left:50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/images/assets/CurrencyRateChartsWhite.png);\n"
"    background-repeat: none;\n"
"    padding-left: 50px;\n"
"};")
        self.CurrencyRateCharts_button.setObjectName("CurrencyRateCharts_button")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.CurrencyRateCharts_button)
        self.CurrencyConverter_button = QtWidgets.QPushButton(self.left_menu_top_buttons)
        self.CurrencyConverter_button.setMinimumSize(QtCore.QSize(0, 40))
        self.CurrencyConverter_button.setMaximumSize(QtCore.QSize(16777215, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.CurrencyConverter_button.setFont(font)
        self.CurrencyConverter_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CurrencyConverter_button.setStyleSheet("QPushButton {\n"
"    background-image: url(:/images/assets/CurrencyConverterBlack.png);\n"
"    background-repeat: none;\n"
"    padding-left: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-image: url(:/images/assets/CurrencyConverterWhite.png);\n"
"    background-repeat: none;\n"
"    padding-left: 50px;\n"
"}")
        self.CurrencyConverter_button.setObjectName("CurrencyConverter_button")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.CurrencyConverter_button)
        self.verticalLayout_2.addWidget(self.left_menu_top_buttons)
        self.Suggestions_button = QtWidgets.QPushButton(self.left_side_menu)
        self.Suggestions_button.setMinimumSize(QtCore.QSize(0, 30))
        self.Suggestions_button.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.Suggestions_button.setFont(font)
        self.Suggestions_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Suggestions_button.setStyleSheet("QPushButton {\n"
"    border-radius: 15px;\n"
"    background-image: url(:/images/assets/SuggestionsBlack.png);\n"
"    background-repeat: none;\n"
"    background-position: center left;\n"
"    padding-left: 50px;\n"
"}\n"
"QPushButton:hover {\n"
"    border-radius: 15px;\n"
"    background-image: url(:/images/assets/SuggestionsWhite.png);\n"
"    background-repeat: none;\n"
"    padding-left: 50px;\n"
"}")
        self.Suggestions_button.setObjectName("Suggestions_button")
        self.verticalLayout_2.addWidget(self.Suggestions_button)
        self.horizontalLayout.addWidget(self.left_side_menu)
        self.center_main_items = QtWidgets.QFrame(self.main_body)
        self.center_main_items.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.center_main_items.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.center_main_items.setFrameShadow(QtWidgets.QFrame.Raised)
        self.center_main_items.setObjectName("center_main_items")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.center_main_items)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(self.center_main_items)
        self.stackedWidget.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.stackedWidget.setObjectName("stackedWidget")
        self.CurrencyRateCharts_page = QtWidgets.QWidget()
        self.CurrencyRateCharts_page.setObjectName("CurrencyRateCharts_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.CurrencyRateCharts_page)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.CurrencyRateCharts = QtWidgets.QLabel(self.CurrencyRateCharts_page)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.CurrencyRateCharts.setFont(font)
        self.CurrencyRateCharts.setObjectName("CurrencyRateCharts")
        self.verticalLayout_5.addWidget(self.CurrencyRateCharts, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.graphicsView = PlotWidget(self.CurrencyRateCharts_page)
        self.graphicsView.setStyleSheet("background-color: white;\n"
"color: white;")
        self.graphicsView.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.graphicsView.setObjectName("graphicsView")
        self.verticalLayout_5.addWidget(self.graphicsView)
        self.date_frame = QtWidgets.QFrame(self.CurrencyRateCharts_page)
        self.date_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.date_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.date_frame.setObjectName("date_frame")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.date_frame)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.beggining_with = QtWidgets.QLabel(self.date_frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.beggining_with.setFont(font)
        self.beggining_with.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.beggining_with.setObjectName("beggining_with")
        self.horizontalLayout_13.addWidget(self.beggining_with)
        self.dateEdit = QtWidgets.QDateEdit(self.date_frame)
        self.dateEdit.setMinimumSize(QtCore.QSize(180, 30))
        self.dateEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.dateEdit.setFont(font)
        self.dateEdit.setStyleSheet("border: none;\n"
"border-radius: 15px;\n"
"background-color: rgb(240, 240, 240);\n"
"")
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_13.addWidget(self.dateEdit)
        self.verticalLayout_5.addWidget(self.date_frame, 0, QtCore.Qt.AlignHCenter)
        self.error_label_2 = QtWidgets.QLabel(self.CurrencyRateCharts_page)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.error_label_2.setFont(font)
        self.error_label_2.setStyleSheet("color: rgb(154, 0, 0)")
        self.error_label_2.setText("")
        self.error_label_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.error_label_2.setObjectName("error_label_2")
        self.verticalLayout_5.addWidget(self.error_label_2)
        self.BuildAGraph = QtWidgets.QPushButton(self.CurrencyRateCharts_page)
        self.BuildAGraph.setMinimumSize(QtCore.QSize(300, 40))
        self.BuildAGraph.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.BuildAGraph.setFont(font)
        self.BuildAGraph.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.BuildAGraph.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 255), stop:1 rgba(14, 177, 255, 255));\n"
"color: #fff;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 200), stop:1 rgba(14, 177, 255, 200));\n"
"}")
        self.BuildAGraph.setObjectName("BuildAGraph")
        self.verticalLayout_5.addWidget(self.BuildAGraph, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.CurrencyRateCharts_page)
        self.CurrencyConverter_page = QtWidgets.QWidget()
        self.CurrencyConverter_page.setObjectName("CurrencyConverter_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.CurrencyConverter_page)
        self.verticalLayout_6.setContentsMargins(0, -1, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.CurrencyConverter_page)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_6.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.frame = QtWidgets.QFrame(self.CurrencyConverter_page)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.input = QtWidgets.QLineEdit(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.input.sizePolicy().hasHeightForWidth())
        self.input.setSizePolicy(sizePolicy)
        self.input.setMinimumSize(QtCore.QSize(400, 40))
        self.input.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.input.setFont(font)
        self.input.setStyleSheet("border-radius: 20px;\n"
"color: black;\n"
"border: 2px solid rgb(66, 194, 238);")
        self.input.setText("")
        self.input.setAlignment(QtCore.Qt.AlignCenter)
        self.input.setObjectName("input")
        self.verticalLayout_8.addWidget(self.input, 0, QtCore.Qt.AlignHCenter)
        self.output = QtWidgets.QLineEdit(self.frame)
        self.output.setMinimumSize(QtCore.QSize(400, 40))
        self.output.setMaximumSize(QtCore.QSize(400, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.output.setFont(font)
        self.output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.output.setStyleSheet("border-radius: 20px;\n"
"color: black;\n"
"border: 2px solid rgb(66, 194, 238);")
        self.output.setText("")
        self.output.setAlignment(QtCore.Qt.AlignCenter)
        self.output.setReadOnly(True)
        self.output.setObjectName("output")
        self.verticalLayout_8.addWidget(self.output, 0, QtCore.Qt.AlignHCenter)
        self.error_label = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.error_label.setFont(font)
        self.error_label.setStyleSheet("color: rgb(154, 0, 0)")
        self.error_label.setText("")
        self.error_label.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.error_label.setObjectName("error_label")
        self.verticalLayout_8.addWidget(self.error_label)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem)
        self.convert = QtWidgets.QPushButton(self.frame)
        self.convert.setMinimumSize(QtCore.QSize(300, 40))
        self.convert.setMaximumSize(QtCore.QSize(300, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.convert.setFont(font)
        self.convert.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.convert.setStyleSheet("QPushButton{\n"
"border-radius: 20px;\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 255), stop:1 rgba(14, 177, 255, 255));\n"
"color: #fff;\n"
"}\n"
"QPushButton:pressed{\n"
"background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 200), stop:1 rgba(14, 177, 255, 200));\n"
"}")
        self.convert.setObjectName("convert")
        self.verticalLayout_8.addWidget(self.convert, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_6.addWidget(self.frame)
        self.stackedWidget.addWidget(self.CurrencyConverter_page)
        self.Suggestions_page = QtWidgets.QWidget()
        self.Suggestions_page.setObjectName("Suggestions_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.Suggestions_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.Suggestions_page)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.frame_2 = QtWidgets.QFrame(self.Suggestions_page)
        self.frame_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-radius: 50px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.telegram = QtWidgets.QPushButton(self.frame_2)
        self.telegram.setMinimumSize(QtCore.QSize(100, 100))
        self.telegram.setMaximumSize(QtCore.QSize(100, 100))
        self.telegram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.telegram.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(43, 162, 222);\n"
"}")
        self.telegram.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/assets/telegram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.telegram.setIcon(icon6)
        self.telegram.setIconSize(QtCore.QSize(70, 70))
        self.telegram.setObjectName("telegram")
        self.horizontalLayout_11.addWidget(self.telegram)
        self.vk = QtWidgets.QPushButton(self.frame_2)
        self.vk.setMinimumSize(QtCore.QSize(100, 100))
        self.vk.setMaximumSize(QtCore.QSize(100, 100))
        self.vk.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.vk.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(0, 119, 255);\n"
"}")
        self.vk.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/images/assets/vk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.vk.setIcon(icon7)
        self.vk.setIconSize(QtCore.QSize(50, 50))
        self.vk.setObjectName("vk")
        self.horizontalLayout_11.addWidget(self.vk)
        self.instagram = QtWidgets.QPushButton(self.frame_2)
        self.instagram.setMinimumSize(QtCore.QSize(100, 100))
        self.instagram.setMaximumSize(QtCore.QSize(100, 100))
        self.instagram.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.instagram.setStyleSheet("QPushButton {\n"
"    background-color: rgb(208, 208, 208);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: qlineargradient(spread:pad, x1:1, y1:0, x2:0, y2:1, stop:0 rgba(235, 0, 255, 255), stop:0.850746 rgba(255, 200, 51, 255))\n"
"}")
        self.instagram.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/images/assets/instagram.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.instagram.setIcon(icon8)
        self.instagram.setIconSize(QtCore.QSize(50, 50))
        self.instagram.setObjectName("instagram")
        self.horizontalLayout_11.addWidget(self.instagram)
        self.verticalLayout_4.addWidget(self.frame_2)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.stackedWidget.addWidget(self.Suggestions_page)
        self.verticalLayout_3.addWidget(self.stackedWidget)
        self.horizontalLayout.addWidget(self.center_main_items)
        self.right_side_menu = QtWidgets.QFrame(self.main_body)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_side_menu.sizePolicy().hasHeightForWidth())
        self.right_side_menu.setSizePolicy(sizePolicy)
        self.right_side_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.right_side_menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.right_side_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_side_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_side_menu.setObjectName("right_side_menu")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.right_side_menu)
        self.verticalLayout_10.setContentsMargins(0, 55, 0, 0)
        self.verticalLayout_10.setSpacing(7)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.i_have = QtWidgets.QFrame(self.right_side_menu)
        self.i_have.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.i_have.setFrameShadow(QtWidgets.QFrame.Raised)
        self.i_have.setObjectName("i_have")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.i_have)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.i_have_label = QtWidgets.QLabel(self.i_have)
        self.i_have_label.setMinimumSize(QtCore.QSize(0, 0))
        self.i_have_label.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.i_have_label.setFont(font)
        self.i_have_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.i_have_label.setObjectName("i_have_label")
        self.horizontalLayout_9.addWidget(self.i_have_label)
        self.currency_input = QtWidgets.QComboBox(self.i_have)
        self.currency_input.setMinimumSize(QtCore.QSize(100, 40))
        self.currency_input.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currency_input.setFont(font)
        self.currency_input.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.currency_input.setStyleSheet("QComboBox{\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    border: 2px solid rgb(66, 194, 238);\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/images/assets/down.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin-right: 15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 2px solid rgb(66, 194, 238);\n"
"}\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border: 1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox::QListView:item{\n"
"    padding-left: 10px;\n"
"    background-color: #fff;\n"
"}\n"
"QComboBox::QListView:item:hover{\n"
"    padding-left: 20px;\n"
"    background-color: rgb(66, 194, 238);\n"
"}")
        self.currency_input.setObjectName("currency_input")
        self.horizontalLayout_9.addWidget(self.currency_input)
        self.verticalLayout_10.addWidget(self.i_have, 0, QtCore.Qt.AlignTop)
        self.i_want_to_buy = QtWidgets.QFrame(self.right_side_menu)
        self.i_want_to_buy.setMinimumSize(QtCore.QSize(50, 0))
        self.i_want_to_buy.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.i_want_to_buy.setFrameShadow(QtWidgets.QFrame.Raised)
        self.i_want_to_buy.setObjectName("i_want_to_buy")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.i_want_to_buy)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.i_want_to_buy_label = QtWidgets.QLabel(self.i_want_to_buy)
        self.i_want_to_buy_label.setMaximumSize(QtCore.QSize(0, 16777215))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.i_want_to_buy_label.setFont(font)
        self.i_want_to_buy_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.i_want_to_buy_label.setObjectName("i_want_to_buy_label")
        self.horizontalLayout_10.addWidget(self.i_want_to_buy_label)
        self.currency_output = QtWidgets.QComboBox(self.i_want_to_buy)
        self.currency_output.setMinimumSize(QtCore.QSize(100, 40))
        self.currency_output.setMaximumSize(QtCore.QSize(100, 40))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.currency_output.setFont(font)
        self.currency_output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.currency_output.setStyleSheet("QComboBox{\n"
"    border-radius: 20px;\n"
"    color: black;\n"
"    border: 2px solid rgb(66, 194, 238);\n"
"}\n"
"QComboBox::drop-down{\n"
"    border: 0px;\n"
"}\n"
"QComboBox::down-arrow {\n"
"    image: url(:/images/assets/down.png);\n"
"    width: 20px;\n"
"    height: 20px;\n"
"    margin-right: 15px;\n"
"}\n"
"QComboBox:on {\n"
"    border: 2px solid rgb(66, 194, 238);\n"
"}\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border: 1px solid rgba(0, 0, 0, 10%);\n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;\n"
"}\n"
"QComboBox::QListView:item{\n"
"    padding-left: 10px;\n"
"    background-color: #fff;\n"
"}\n"
"QComboBox::QListView:item:hover{\n"
"    padding-left: 20px;\n"
"    background-color: rgb(66, 194, 238);\n"
"}")
        self.currency_output.setObjectName("currency_output")
        self.horizontalLayout_10.addWidget(self.currency_output)
        self.verticalLayout_10.addWidget(self.i_want_to_buy, 0, QtCore.Qt.AlignTop)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem3)
        self.bottom_right_menu = QtWidgets.QFrame(self.right_side_menu)
        self.bottom_right_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.bottom_right_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottom_right_menu.setObjectName("bottom_right_menu")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.bottom_right_menu)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.swap = QtWidgets.QPushButton(self.bottom_right_menu)
        self.swap.setMinimumSize(QtCore.QSize(50, 50))
        self.swap.setMaximumSize(QtCore.QSize(50, 50))
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.swap.setFont(font)
        self.swap.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.swap.setStyleSheet("QPushButton {\n"
"    background-color: rgb(240, 255, 240);\n"
"    border-radius: 25px;\n"
"    background-color: rgb(240, 240, 240);\n"
"    color: #000;\n"
"    transition: all 0.5s;\n"
"    background-image: url(:/images/assets/exchangeBlack.png);\n"
"    background-repeat: none;\n"
"    background-position: center right;\n"
"    padding-right: 50px\n"
"}\n"
"QPushButton:hover {\n"
"    background-color:qlineargradient(spread:pad, x1:0, y1:0.563, x2:0.985075, y2:0.591, stop:0 rgba(0, 227, 147, 255), stop:1 rgba(14, 177, 255, 255));\n"
"    color: #fff;\n"
"    background-image: url(:/images/assets/exchangeWhite.png);\n"
"    background-repeat: none;\n"
"}\n"
"QPushButton:pressed {\n"
"    border-bottom: 2px solid rgb(0, 234, 153);\n"
"}")
        self.swap.setObjectName("swap")
        self.horizontalLayout_12.addWidget(self.swap)
        self.verticalLayout_10.addWidget(self.bottom_right_menu)
        self.horizontalLayout.addWidget(self.right_side_menu)
        self.verticalLayout.addWidget(self.main_body)
        self.main_footer = QtWidgets.QFrame(self.centralwidget)
        self.main_footer.setMinimumSize(QtCore.QSize(0, 30))
        self.main_footer.setMaximumSize(QtCore.QSize(16777215, 30))
        self.main_footer.setStyleSheet("QFrame{\n"
"background-color: rgb(240, 255, 240);\n"
"}")
        self.main_footer.setFrameShape(QtWidgets.QFrame.Panel)
        self.main_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_footer.setObjectName("main_footer")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.main_footer)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.main_footer)
        font = QtGui.QFont()
        font.setFamily("SF Pro Display")
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("padding-left: 10px;\n"
"color: rgb(150, 150, 150)")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.size_grip = QtWidgets.QFrame(self.main_footer)
        self.size_grip.setMinimumSize(QtCore.QSize(10, 10))
        self.size_grip.setMaximumSize(QtCore.QSize(10, 10))
        self.size_grip.setSizeIncrement(QtCore.QSize(0, 0))
        self.size_grip.setStyleSheet("background-color: rgb(240, 255, 240);")
        self.size_grip.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.size_grip.setObjectName("size_grip")
        self.horizontalLayout_7.addWidget(self.size_grip, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.verticalLayout.addWidget(self.main_footer)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.RateX.setText(_translate("MainWindow", "RateX"))
        self.Rate.setText(_translate("MainWindow", "Rate"))
        self.CurrencyRateCharts_button.setText(_translate("MainWindow", "CURRENCY RATE CHARTS"))
        self.CurrencyConverter_button.setText(_translate("MainWindow", "CURRENCY CONVERTER"))
        self.Suggestions_button.setText(_translate("MainWindow", "SUGGESTIONS"))
        self.CurrencyRateCharts.setText(_translate("MainWindow", "CURRENCY RATE CHARTS"))
        self.beggining_with.setText(_translate("MainWindow", "BEGGINING WITH:"))
        self.BuildAGraph.setText(_translate("MainWindow", "BUILD A GRAPH"))
        self.label_2.setText(_translate("MainWindow", "CURRENCY CONVERTER"))
        self.convert.setText(_translate("MainWindow", "CONVERT"))
        self.label_3.setText(_translate("MainWindow", "SUGGESTIONS"))
        self.i_have_label.setText(_translate("MainWindow", "from currency:  "))
        self.i_want_to_buy_label.setText(_translate("MainWindow", "into currency:  "))
        self.swap.setText(_translate("MainWindow", "SWAP CURRENCIES"))
        self.label.setText(_translate("MainWindow", "Designed by Yavorsky Daniil in California"))
from pyqtgraph import PlotWidget
import assets_rc
